# -*- coding: utf-8 -*-
"""Youtube Statistics API call.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KmV6XetjRoYT10cct-Di69BwCa5nGrT_
"""

import requests
import pandas as pd
import time

API_KEY = 'AIzaSyC-vsWaqFYYJRwELqcf7_f1r_C-2OFLa_U'
CHANNEL_ID = 'UC9x0AN7BWHpCDHSm9NiJFJQ' ### amazon youtube channel id
pageToken = ''
url = 'https://www.googleapis.com/youtube/v3/search?key='+API_KEY+'&channelId='+CHANNEL_ID+'&part=snippet,id&order=date&maxResults=10000'+pageToken
response = requests.get(url).json()

df = pd.DataFrame(columns=['id', 'title','date','views','likes','dislikes'])
for video in response['items']:
  if video['id']['kind'] == 'youtube#video': 
    video_id = video['id']['videoId'] ### video id 
    video_title = video['snippet']['title']
    video_title = str(video_title).replace('&amp;','') ### title
    video_date = video['snippet']['publishTime']
    video_date = str(video_date).split('T')[0] ### upload date

    ### views, comments, likes y dislikes

    url2 = 'https://www.googleapis.com/youtube/v3/videos?id='+video_id+'&part=statistics&key='+API_KEY
    response2 = requests.get(url2).json()

    view_count = response2['items'][0]['statistics']['viewCount']
    like_count = response2['items'][0]['statistics']['likeCount']
    dislike_count = response2['items'][0]['statistics']['commentCount']

    ### guardando en pandas df

    df = df.append({'id':video_id,
               'title': video_title,
               'date': video_date,
               'views': view_count,
               'likes':like_count,
               'dislikes': dislike_count
               },ignore_index=True)

df.head()